name: Install and Configure Chrome Remote Desktop

on:
  workflow_dispatch:

jobs:
  build:
    name: Install Chrome Remote Desktop
    runs-on: windows-latest

    steps:
      - name: Download Chrome Remote Desktop Installer
        run: |
          Invoke-WebRequest -Uri "https://dl.google.com/chrome-remote-desktop/chromeremotedesktophost.msi" -OutFile "chromeremotedesktophost.msi"

      - name: Install Chrome Remote Desktop
        run: |
          msiexec /i "chromeremotedesktophost.msi" /quiet
